print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? "))
tip = int(input("How much tip would you like to give? "))
people  = int(input("How many people to split the bill? "))
bill *= (tip / 100 + 1)
print(f"Each person should pay: ${round((bill / people),2)}")